# Generated by Django 3.2.11 on 2022-01-31 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220131_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
